name: agu-ossi-2020

channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pandas
  - requests
  - numpy
  - scipy
  - matplotlib
  - ipywidgets
  - mkl
  - discretize
  - geoana
  - SimPEG
  - pymatsolver
